version: '3.8'

services:
    de1soc_yocto:
        container_name: de1soc_yocto
        image: ${USER}/de1soc_yocto
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        stdin_open: true          ## docker run -i
        tty: true                 ## docker run -t
        working_dir: "/home/${USER}"
        #privileged: true
        environment:
          - USER
        env_file:
          - .env
        volumes:
          ## folders not need to be around
          - ~/.gitconfig:/home/$USER/.gitconfig:ro
          - ~/.ssh:/home/$USER/.ssh
          - ./poky:/home/$USER/poky
          ## folder must be around
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
          - type: bind
            source: ./meta-lothars-configs
            target: /home/$USER/meta-lothars-configs
