version: '3.8'

services:
    de1soc_yocto:
        container_name: de1soc_yocto
        image: ${USER}/de1soc_yocto
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: $USER

        user: $USER
        stdin_open: true          ## docker run -i
        tty: true                 ## docker run -t
        working_dir: /home/$USER
        #privileged: true

        environment:
          - USER

        volumes:
          - ~/.gitconfig:/home/$USER/.gitconfig:ro
          - ~/.ssh:/home/$USER/.ssh:ro
          - ./poky:/home/$USER/poky  ## folder does not need to be around
          - type: bind
            source: ./meta-lothars-configs ## folder must be around
            target: /home/$USER/meta-lothars-configs
